sbintuitions/flexeval

flexeval/scripts/flexeval_lm.py
I think `config.json` should be overwritten when running `flexeval_lm ... --force true`, but it seems that the overwrite process was missing, so I suggest adding it.
=> Fixed a bug where `config.json` was not overwritten

flexeval/core/chat_dataset/base.py, flexeval/core/evaluate_chat_response.py, flexeval/core/few_shot_generator/balanced.py, flexeval/core/few_shot_generator/base.py, flexeval/core/few_shot_generator/rand.py, flexeval/scripts/flexeval_lm.py, tests/core/few_show_generator/test_rand.py, tests/core/test_evaluate_functions.py, tests/dummy_modules/chat_dataset.py, tests/dummy_modules/lm.py, tests/dummy_modules/multiple_choice_dataset.py
チャット形式の評価時に、Few-Shot 学習用のメッセージを入れられるようにします。
これにより、以下のような形式で few-shot サンプル付きのメッセージ入力を `LanguageModel.batch_generate_chat_response` に入れることができます。
```python
[
{"role": "user", "content": "This is a dog."},
{"role": "assistant", "content": "これは犬です。"},
{"role": "user", "content": "This is a cat."},
{"role": "assistant", "content": "これは猫です。"},
{"role": "user", "content": This is a pig.}
]
```
* `FewShotGenerator` に `ChatDataset` を渡して `ChatInstance` をサンプルできるように拡張
* `evaluate_chat_response` に `FewShotGenerator` を組み込んで入力メッセージに few-shot 事例を追加するロジックを実装
* 上記に関連するテストの拡充
=> `ChatResponse` の評価時に `few_shot_generator` を指定できるようにする

flexeval/scripts/common.py, flexeval/scripts/flexeval_lm.py, tests/scripts/test_flexeval_lm.py
`--eval_setup` に `EvalSetup` および `dict[str, EvalSetup]` のパースを任せるのは、コードが複雑になり、利用者にとっても仕様に曖昧性が出て使いずらいところがあるのではないかと考えた。
これらを `--eval_setup` と `--eval_setups` に分けて整理をした。
=> `flexeva_lm` の `EvalSetup` 用のインターフェイスを更新

flexeval/core/metric/code_eval.py, flexeval/preset_configs/EvalSetup/code_generation/jhumaneval.jsonnet, flexeval/preset_configs/EvalSetup/code_generation/jhumaneval_tab_indent.jsonnet, flexeval/preset_configs/EvalSetup/code_generation/openai_humaneval.jsonnet, flexeval/preset_configs/EvalSetup/code_generation/openai_humaneval_tab_indent.jsonnet, tests/core/metric/test_code_eval.py
Enhance the flexibility of the code snippet to be evaluated by embedding `lm_output` into the template
=> Refactor `CodeEval` for enhanced flexibility

flexeval/__init__.py, flexeval/core/evaluate_from_data.py, flexeval/core/evaluate_from_file.py, flexeval/scripts/flexeval_file.py, tests/core/test_evaluate_functions.py, tests/dummy_modules/eval_data_loader.py, tests/scripts/test_flexeval_file.py
`flexeval_file` をファイルの入力以外にも拡張するための準備です。
まずは、外から見た挙動を変えずに、中のロジックを整理しました。
- `evaluate_from_file` -> `evaluate_from_data` に変え、関数の入力をファイルではなく、データにしました
- `EvalDataLoader` という抽象クラスを作り、そこを差し替えることでファイル以外からでも評価用のデータを読み込めるようにしました
=> Refactor `flexeval_file`

poetry.lock, pyproject.toml
現状ではubunutu20.04系で動かした際に次のようなエラーメッセージが出ます
```
WARNING 07-24 21:16:52 _custom_ops.py:14] Failed to import from vllm._C with ImportError("/usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/local/lib/python3.10/dist-packages/vllm/_C.abi3.so)")
```
これによってvllmの機能が制限されてしまっています。 (llamaは動かない)
[vllm側の対応PR](https://github.com/vllm-project/vllm/pull/6517) を取り込んだ0.5.3系以上のバージョンに依存vllmバージョンをあげておきたいです。0.5.3以上であれば問題ないですが、とりあえず最新のメンテナンスパッチ等を当てられた0.5.3.post1を依存に入れます。
=> vllmのバージョンを上げる

flexeval/core/language_model/vllm_model.py
We do not hard-code `trust_remote_code=True` for a security reason and let users set it from `model_kwargs`.
=> Remove `trust_remote_code=True` from VLLM

flexeval/core/language_model/base.py, flexeval/core/language_model/hf_lm.py, flexeval/core/language_model/openai_chatgpt.py, flexeval/core/language_model/vllm_model.py, tests/core/language_model/test_hf_lm.py, tests/core/language_model/test_vllm_model.py
Sometimes we need to set model-specific generation kwargs to the model.
It is convenient to specify them from `LanguageModel` rather than `gen_kwargs` in `EvalSetup`.
With this PR, now we can write a config like this.
```jsonnet
{
class_path: "HuggingFaceLM",
init_args: {
model: "sbintuitions/sarashina2-7b",
default_gen_kwargs: {top_p: 0.9, temperature: 0.7}
}
}
```
Note that when the same parameters are specified in `gen_kwargs` from `EvalSetup`, `default_gen_kwargs` will be overridden.
=> Introduce `default_gen_kwargs` to `LanguageModel`

flexeval/core/language_model/__init__.py, flexeval/core/language_model/openai_api.py, tests/core/language_model/test_openai_completion_api.py
This pull request adds a `LanguageModel` implementation of OpenAI's Completion API. 
OpenAI regards Completion API as a legacy API, however, we can make use of this API via VLLM.
=> Support OpenAI's Completion API

flexeval/core/language_model/vllm_model.py
In #75, enable_chunked_prefill was set to True for VLLM initialization, but chunked prefill and sliding window can't be enabled together, causing errors for some models.
cf. https://github.com/vllm-project/vllm/blob/main/vllm/engine/arg_utils.py#L1078-L1083
This update sets disable_sliding_window to True by default.
=> Set the default value of `disable_sliding_window` to `True` in `VLLM` class

flexeval/core/language_model/openai_batch_api.py
This will make stack traces a bit cleaner.
Otherwise, we get this.
```bash
Exception ignored in: <function OpenAIChatBatchAPI.__del__ at 0x143efa820>
Traceback (most recent call last):
File ".../.venv/lib/python3.9/site-packages/flexeval/core/language_model/openai_batch_api.py", line 209, in __del__
self.close()
File ".../.venv/lib/python3.9/site-packages/flexeval/core/language_model/openai_batch_api.py", line 202, in close
self.temp_jsonl_file.close()
AttributeError: 'OpenAIChatBatchAPI' object has no attribute 'temp_jsonl_file'
```
=> Check if temp file exists before close it in `OpenAIChatBatchAPI`

flexeval/core/metric/llm_score.py
In the `LLMScore` and `ChatLLMScore` classes, I found instances where the hard-coded string "category" was used as a key, instead of the string specified by `category_key`. I fixed it.
=> Fix bug related to `category_key` in `LLMScore` and `ChatLLMScore`

flexeval/core/metric/__init__.py, flexeval/core/metric/base.py, flexeval/core/metric/llm_label.py, flexeval/core/metric/llm_score.py, tests/core/metric/test_llm_label.py
Add `LLMLabel` and `ChatLLMLabel`.
Different from `LLMScore` and `ChatLLMScore`, they deal with labels on a non-Likert scale.
You can define label names and assign a score to each label. The mean score and the label distribution are output.
=> Classification-based evaluation using `LanguageModel`

flexeval/core/metric/code_eval.py
Some may wants to change evaluate_module to variants of `code_eval` module.
=> Add evaluate_module option to CodeEval class

flexeval/core/metric/llm_score.py, tests/core/metric/test_llm_score.py
Fix a bug in the `ChatLLMScore` and `ChatLLMLabel` classes where the `system_message` rendered for the first iteration of a batch was reused in subsequent iterations.
=> Fix bug: `system_message` rendering issue in `ChatLLMScore` and `ChatLLMLabel`

flexeval/core/reward_model/sequence_classification.py, tests/core/reward_model/test_sequence_classification.py
The previous implementation assumed that all inputs in the batch had the same length, which caused failures when they did not.
This PR addresses and resolves that issue by adding `padding=True` to `apply_chat_template`.
This PR also specify `return_dict=True` in `apply_chat_template` to explicitly  get `attention_mask` for the input.
=> Debug `SequenceClassificationRewardModel`

flexeval/core/language_model/openai_api.py, flexeval/core/language_model/openai_batch_api.py
With the recent update of OpenAI's chat completion API, the `max_tokens` parameter has been deprecated. 
cf. https://platform.openai.com/docs/api-reference/chat/create#chat-create-max_tokens
We need update our implementation to use the replacement parameter, `max_completion_tokens`.
For previous models like `gpt-4o`, there is no change in behavior. However, the `o1` series models do not accept the `max_tokens` parameter and requires `max_completion_tokens`, making this update essential.
The following models have been verified to generate responses successfully using the `mt-ja` benchmark data:
* o1-mini-2024-09-12 (via `OpenAIChatAPI` class, `max_new_tokens=10000`)
* gpt-4o-2024-08-06 (via `OpenAIChatAPI` class)
* gpt-4o-2024-08-06 (via `OpenAIChatBatchAPI` class)
Related issue: …
=> Replace Deprecated parameter `max_tokens` with `max_completion_tokens` for OpenAI API

flexeval/core/prompt_template/jinja2.py
We don't have to call `JINJA2_ENV.from_string` for every input_dict.
=> Cache jinja2 template

flexeval/core/chat_dataset/template_based.py
`TemplateChatDataset` itself does not use HuggingFace datasets.
=> Update docstring of `TemplateChatDataset`

flexeval/core/metric/repetition_count.py, tests/core/metric/test_repetition_count.py
Currently, `get_most_repeated_pattern` does not support input with spaces and symbols like ` ` and ` _ _ _ _`.
```
In [9]: get_most_repeated_pattern(' ')
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[9], line 1
----> 1 get_most_repeated_pattern(' ')
Cell In[4], line 11, in get_most_repeated_pattern(text, threshold_length)
7         continue
8     counter[subtext] += 1
---> 11 subtext, count = counter.most_common(1)[0]
14 return subtext, count
IndexError: list index out of range
```
With this PR, the function returns empty substring and count of 0.
=> Fix `get_most_repeated_pattern`

flexeval/core/language_model/openai_batch_api.py, tests/core/language_model/test_openai_chatgpt_batch_api.py
- Fixed `OpenAIChatBatchAPI` class to use `gen_kwargs` when calling API.
- `gen_kwargs` is initialized by `default_gen_kwargs` and updated by `kwargs`.
- Updated test for `OpenAIChatBatchAPI`.
=> re-fix OpenAIChatBatchAPI class

poetry.lock, pyproject.toml
This is a workaround to install the transformer package with the ja component in aarch64 Linux environment.
The Huggingface Transformer supports several components. Flexeval enables "ja" component. It depends on sudachipy 0.6.6 or later. My Python 3 runtime selects sudachipy 0.6.9.
In PyPI, no pre-built binary is provided for sudachipy 0.6.9, thus Pip downloads the source distribution and attempts to build it.
https://pypi.org/project/SudachiPy/0.6.9/#files
It hits FTBFS of sudachipy 0.6.9 due to invalid entries in Cargo.toml.
https://github.com/WorksApplications/sudachi.rs/issues/290
The issue has been fixed in sudachipy 0.6.10. Let us use the version.
=> Use sudachipy v0.6.10 or later to fix FTBFS in aarch64 Linux environment

flexeval/core/evaluate_chat_response.py, flexeval/core/evaluate_generation.py, tests/core/test_evaluate_functions.py
Output `finish_reason` in the result to gain insights into how the LM stops generation.
With this PR,
* Each line in `outputs.jsonl` includes a finish_reason indicating how the generation ended.
* `metrics.json` contains `finish_reason_ratio-{finish_reason}` values, representing the fraction of each finish reason.
* For example, a high `finish_reason_ratio-length` suggests that generation stops because it reaches `max_new_tokens`, whether intentionally or not.
=> Save `finish_reason` statistics

flexeval/core/language_model/hf_lm.py, flexeval/core/language_model/vllm_model.py, tests/core/language_model/test_hf_lm.py
The generated text in `HuggingFaceLM` and `VLLM` is decoded using the following code:
```
decoded_text = self.tokenizer.decode(output_tokens, skip_special_tokens=False)
```
However, the issue is that the decoded output of some tokenizers depends on the surrounding context of the tokens.
Example:
```
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("llm-jp/llm-jp-3-3.7b")
prefix = [813, 19229, 5896, 18]
continuation = [277, 617, 36803]
print(tokenizer.decode(continuation))
print(tokenizer.decode(prefix))
print(tokenizer.decode(prefix + continuation))
```
As a result, decoding tokens in isolation may lead to incorrect formatting.
This behavior is influenced by the "add_prefix_space" option or the tokenizer’s post-processing logic.
Solution:
To ensure correct …
=> Introduce `decode_for_lm_continuation`

flexeval/core/metric/tokenizer/__init__.py, flexeval/core/metric/tokenizer/tiktoken_tokenizer.py, flexeval/core/metric/tokenizer/transformers_tokenizer.py, tests/core/metric/tokenizer/test_tiktoken_tokenizer.py, tests/core/metric/tokenizer/test_transformers_tokenizer.py
This pull request introduces two new tokenizers: `TiktokenTokenizer` and `TransformersTokenizer` classes.
New tokenizers added:
* [`flexeval/core/metric/tokenizer/__init__.py`](diffhunk://#diff-310ca6115d3002c841e50cc1e0d677aa35557c819bbfdcad23318c30b9c2d3f1R4-R5): Added imports for `TiktokenTokenizer` and `TransformersTokenizer`.
* [`flexeval/core/metric/tokenizer/tiktoken_tokenizer.py`](diffhunk://#diff-99fb318747a160bfb1b7ef29c653a0a946d9612baaf28ccc4ebf62a6ea7d10d9R1-R23): Introduced the `TiktokenTokenizer` class, which supports tokenization using the `tiktoken` library.
* [`flexeval/core/metric/tokenizer/transformers_tokenizer.py`](diffhunk://#diff-48ef00fca2a514f79f55144c49dd067c47dbe726e9300ba24bf71024b169c458R1-R20): Introduced the `TransformersTokenizer` class, which supports …
=> Add tokenizers

flexeval/core/language_model/base.py, flexeval/core/language_model/hf_lm.py, flexeval/core/language_model/litellm_api.py, flexeval/core/language_model/openai_api.py, flexeval/core/language_model/openai_batch_api.py, flexeval/core/language_model/vllm_model.py, tests/core/language_model/base.py
Now we can specify `StringProcessor` in `LanguageModel`.
The processing is implemented in the interface method `complete_text` and `generate_chat_response`, applied to all `LanguageModel` classes.
`LMOutput` has the additional field `raw_text` which is convenient to check the output before processing.
=> Add `StringProcessor` to `LanguageModel`

flexeval/core/evaluate_chat_response.py, flexeval/core/evaluate_generation.py
At #163, StringProcessor can be applied to LanguageModel output.
In this PR, I modify `evaluate_chat_response()` and `evaluate_generation()` to keep raw outputs before formatting.
=> Logging raw `LanguageModel` outputs before formatting

flexeval/core/metric/bleu.py, flexeval/core/metric/char_f1.py, flexeval/core/metric/exact_match.py, tests/core/metric/test_bleu.py, tests/core/metric/test_char_f1.py
Add `lm_output_processor` and `reference_processor` options to `BLEU`.
And allows `CharF1`, `BLEU` to compute category-wise scores.
When these options are not used, the behaviors are the same as previously.
=> Add `category_key` and `*_processor` options to some `Metric` s

examples/sarashina_2_2_evaluation/README.md
This PR fixes a small typo in the README. The script name `evaluate_sarashina_2_2` was incorrect and has been updated to the correct `sarashina_2_2_evaluation` to avoid confusion when running the command.
=> fix: correct script name in README from evaluate_sarashina_2_2 to sarashina_2_2_evaluation

flexeval/core/language_model/hf_lm.py, flexeval/core/language_model/openai_api.py, flexeval/core/language_model/openai_batch_api.py, flexeval/core/language_model/vllm_model.py, tests/core/language_model/test_hf_lm.py, tests/core/language_model/test_openai_api.py, tests/core/language_model/vllm/test_vllm_specific.py
Add a `model_limit_new_tokens` argument to various `LanguageModel` implementations.
This allows `max_new_tokens` —as specified in `EvalSetup`, etc.—to be capped at the model-specific upper limit when it exceeds what the model can handle.
For example, if max_new_tokens is set to 8192 in `EvalSetup`, models like OpenAI's gpt-3.5-turbo may return an error:
```bash
bash
$ poetry run flexeval_lm --eval_setup rakuda-v2-ja --eval_setup.gen_kwargs.max_new_tokens 8192 --language_model OpenAIChatAPI --language_model.model gpt-3.5-turbo-0125
...
2025-04-08 17:48:30.999 | WARNING  | flexeval.core.language_model.openai_api:_retry_on_error:56 - We got an error: Error code: 400 - {'error': {'message': 'max_tokens is too large: 8192. This model supports at most 4096 completion tokens, whereas you …
```
=> Add a parameter to `LanguageModel` to determine the upper limit of `max_new_tokens`

flexeval/core/language_model/vllm_model.py
It is imported within function.
https://github.com/sbintuitions/flexeval/blob/49ac16035f327aa329105d849bab2636b11384f9/flexeval/core/language_model/vllm_model.py#L162
https://github.com/sbintuitions/flexeval/blob/49ac16035f327aa329105d849bab2636b11384f9/flexeval/core/language_model/vllm_model.py#L263
=> Remove top-level import in VLLM

flexeval/core/string_processor/__init__.py, flexeval/core/string_processor/json.py, tests/core/string_processor/test_json.py
This PR adds new string processor called `JsonNormalizer`.
This is mainly for evaluating json-like strings generated by LLMs.
=> Add JsonNormalizer

flexeval/core/metric/exact_match.py, tests/core/metric/test_exact_match.py
This PR allows `ExactMatch` metric to set an arbitrary metric name with `metric_key` to store the mean score in metrics.json.
This functionality makes possible for flexeval users to compute multiple `ExactMatch` in differenct settings at once, e.g. difference string processors.
=> Add `metric_key` in `ExactMatch`

flexeval/core/chat_dataset/base.py, flexeval/core/chat_dataset/chatbot_bench.py, flexeval/core/chat_dataset/sacrebleu_dataset.py, flexeval/core/chat_dataset/template_based.py, flexeval/core/eval_setups.py, flexeval/core/evaluate_chat_response.py, tests/core/test_evaluate_chat_response.py, tests/core/test_evaluate_functions.py, tests/dummy_modules/lm.py
Simplified the `evaluate_chat_response` function by...
* Removed the `require_incremental_response` flag and associated methods from all chat dataset classes.
* The function now automatically find where to insert the model response by looking at the structure of messages.
* Extracted few-shot example insertion into `add_few_shot_messages_to_chat_instance`, streamlining the evaluation flow.
The operation of inserting the model response works like this:
```
[
{"role": "system", "content": "..."},
{"role": "user", "content": "..."},
{"role": "user", "content": "..."},
]
[
{"role": "system", "content": "..."},
{"role": "user", "content": "..."},
{"role": "assistant", "content": "..."},
{"role": "user", "content": "..."},
]
```
I've confirmed no degradation in running some benchmarks.
=> Refactor `evaluate_chat_response`

flexeval/core/language_model/base.py, flexeval/core/language_model/hf_lm.py, flexeval/core/language_model/litellm_api.py, flexeval/core/language_model/openai_api.py, flexeval/core/language_model/openai_batch_api.py, flexeval/core/language_model/vllm_model.py, flexeval/core/language_model/vllm_serve_lm.py
The following line may return [None, None, ...], which is interpreted as True.
https://github.com/sbintuitions/flexeval/blob/a74486951ae3c51b2a4e4191e7bf3d10871aa824/flexeval/core/evaluate_chat_response.py#L120
As a result, the if clause incorrectly assumes that tools are available.
https://github.com/sbintuitions/flexeval/blob/a74486951ae3c51b2a4e4191e7bf3d10871aa824/flexeval/core/language_model/hf_lm.py#L394-L396
To fix this issue, remove the validation step.
=> Remove tool_call validation in `HuggingFaceLM` and fix typing

flexeval/core/evaluate_chat_response.py, flexeval/core/result_recorder/local_recorder.py, flexeval/core/utils/json_util.py, tests/core/utils/test_json_util.py
When using flexeval with multimodal data, the default `json.dumps` suffers from
1. binary data and others that are not supported by json, and
2. bae64 data that are very long and hinders the readability of logs.
This PR adds a customized data handling to overcome these problems by
1. converting binary data and others to str by using `str`, and
2. truncating strings that are longer than 512.
This data handler will be used in the output logging in `LocalRecorder` and the logging of the first instance in `evaluate_chat_response`.
Thanks @ryokan0123 for the feedback!
=> Improve data handling in json.dumps used for logging

flexeval/core/evaluate_chat_response.py, flexeval/core/result_recorder/local_recorder.py, flexeval/core/utils/json_util.py, tests/core/utils/test_json_util.py
https://github.com/sbintuitions/flexeval/pull/230 failed to achieve its goal to truncate base64 strings in JSON by using `default` in `json.dumps`, as default data types such as `str` bypassed `default`.
This PR fixes this issue by customizing `JSONEncoder` to modify inputs of such data types.
=> Add a custom JSON encoder to truncate base64 strings

flexeval/core/language_model/openai_api.py
`gpt-5-chat-latest` のようなFanction calling非対応なOpenAIモデルでのエラー対応．
```
tools is not supported in this model. For a list of supported models, refer to https://platform.openai.com/docs/guides/function-calling#models-supporting-function-calling.
```
toolsが`[]`もしくは`None`の場合，OpenAI APIに渡すtoolsフィールドを削除する．(stop_sequencesと同じ動作)
`gpt-5-chat-latest`にて動作確認済み．
=> Fanction calling非対応OpenAIモデルのエラー対応

flexeval/core/evaluate_chat_response.py, tests/core/test_evaluate_chat_response.py
This PR restores the `raw_lm_output` field in the output JSONL file.
The field existed before https://github.com/sbintuitions/flexeval/pull/225, but appears to have been removed during the refactoring in that PR.
- Add `raw_lm_output` to the outputs when `LMOutput.raw_text` is available, which occurs when `string_processors` is provided to the `LanguageModel`.
- Add a test to ensure that `raw_lm_output` is included in the output and that its content differs from `lm_output`.
=> Restore raw_lm_output in evaluation outputs

flexeval/core/language_model/base.py
`__del__` causes unintended Exception as follows:
```
Exception ignored in: <function LanguageModel.__del__ at 0x125a1273a340>
Traceback (most recent call last):
File "/usr/local/lib/python3.12/dist-packages/flexeval/core/language_model/base.py", line 265, in __del__
File "/usr/local/lib/python3.12/dist-packages/flexeval/core/language_model/hf_lm.py", line 555, in cleanup_resources
AttributeError: 'NoneType' object has no attribute 'is_available'
```
=> Remove `__del__` method

flexeval/core/language_model/openai_api.py
- gpt-5-nano評価時にタイムアウト散見され出力が空になってしまった
- 再実行に関するパラメータをexposeし，設定ファイルから指定できるようにしたい
確認しているAPIエラー(多い順)
- `500 Internal Server Error`(8~9割このエラー)
- `429 Too Many Requests`(1割程度このエラー，service_tier:flex起因のエラー)
- `503 Service Unavailable`(たまに見かけるエラー)
現行の仕様だと最大5回トライしNGだった場合，空の出力`""`を返すようになっている．
特に500が発生する場合は5回以内に収まらないことが多く，空の出力となってしまっていた．
- リトライ関連のパラメータ（`max_num_trials`,`first_wait_time`,`max_wait_time`）をexpose，未指定時は従来の設定値がデフォルト値となるように修正
- 追加で，batch_size=10000などの大きい値が設定されるようになっているため，batch内の進捗確認するためのログを追加（環境変数`OPENAI_PROGRESS_EVERY_N`でログを出力する完了件数を設定可能，未設定時は従来同様batch内の進捗ログ出力なし）
=> OpenAIChatAPIのretryパラメータのexpose
